import { Badge } from '../ui';
import type { NewRecruitParseResult } from '../../types/newRecruit';

export interface ImportPreviewProps {
  result: NewRecruitParseResult;
}

export function ImportPreview({ result }: ImportPreviewProps) {
  const maxUnitsToShow = 5;
  const hasMoreUnits = result.units.length > maxUnitsToShow;
  const unitsToDisplay = result.units.slice(0, maxUnitsToShow);
  const remainingCount = result.units.length - maxUnitsToShow;

  return (
    <div className="rounded-lg border border-success/30 bg-success/5 p-4">
      <div className="mb-3 flex items-center gap-2">
        <CheckCircleIcon className="h-5 w-5 text-success" />
        <span className="font-medium text-success">Valid army list</span>
      </div>

      <div className="space-y-3">
        {/* List Name */}
        <div>
          <h4 className="text-lg font-semibold text-gray-900">{result.listName}</h4>
        </div>

        {/* Metadata Tags */}
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="default">{result.faction}</Badge>
          <Badge variant="default">{result.gameSystem}</Badge>
          <span className="text-sm font-medium text-gray-700">
            {result.totalPoints} pts
          </span>
        </div>

        {/* Units Summary */}
        <div className="border-t border-gray-200 pt-3">
          <p className="mb-2 text-sm font-medium text-gray-700">
            {result.units.length} unit{result.units.length !== 1 ? 's' : ''} found:
          </p>
          <ul className="space-y-1 text-sm text-gray-600">
            {unitsToDisplay.map((unit, index) => (
              <li key={`${unit.name}-${index}`} className="flex justify-between">
                <span>
                  {unit.quantity > 1 ? `${unit.quantity}x ` : ''}
                  {unit.name}
                </span>
                <span className="text-gray-400">{unit.pointsCost} pts</span>
              </li>
            ))}
            {hasMoreUnits && (
              <li className="text-gray-400 italic">
                and {remainingCount} more unit{remainingCount !== 1 ? 's' : ''}...
              </li>
            )}
          </ul>
        </div>

        {/* Source Info */}
        <div className="border-t border-gray-200 pt-3">
          <p className="text-xs text-gray-400">
            Generated by {result.generatedBy} (data v{result.dataVersion})
          </p>
        </div>
      </div>
    </div>
  );
}

function CheckCircleIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      viewBox="0 0 20 20"
      fill="currentColor"
      aria-hidden="true"
    >
      <path
        fillRule="evenodd"
        d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
        clipRule="evenodd"
      />
    </svg>
  );
}

ImportPreview.displayName = 'ImportPreview';
